apiVersion: v1
kind: Service
metadata:
  name: ecoloop-backend
  namespace: default
  labels:
    app: ecoloop-backend
spec:
<<<<<<< HEAD
  type: LoadBalancer
=======
  type: ClusterIP
>>>>>>> 9de2022 (Updated the kubernetes manifest and github action pipeline)
  selector:
    app: ecoloop-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
